"use client";
import { useEffect, useRef, useState } from 'react';
import { flushSync } from 'react-dom';
import { ArrowRight, ArrowUpRight, BookOpen, Check, ChevronRight, CirclePause, Clock3, FileText, History, Layers, Mic, Moon, Plus, RotateCcw, Settings2, Sun, WifiOff, X } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Progress } from '@/components/ui/progress';
import { AlertDialog, AlertDialogContent, AlertDialogTitle, AlertDialogDescription, AlertDialogAction, AlertDialogCancel } from '@/components/ui/alert-dialog';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Switch } from '@/components/ui/switch';
import { Toaster, toast } from 'sonner';
import { practices, notes, recommend, type Practice } from './practices';

type Entry={id:string;practice:number;quantity:number;sentence:string;answers:Record<string,string>;time:string;date:string;revoked?:boolean;skipped?:boolean};
type Review={id:string;note:string;answer:string;rating:string;time:string;due:string;stage:number};
type Saved={entries:Entry[];reviews:Review[];goals:Record<string,number>;courseStart:string};
const initial:Saved={entries:[],reviews:[],goals:{},courseStart:''};
const key='pause-prototype-v1';
function localDate(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`}
function courseDay(start:string){if(!start)return 1;const a=new Date(start+'T12:00:00'),b=new Date(localDate()+'T12:00:00');return Math.floor((Date.UTC(b.getFullYear(),b.getMonth(),b.getDate())-Date.UTC(a.getFullYear(),a.getMonth(),a.getDate()))/86400000)+1;}
function dueDate(days:number){const d=new Date();d.setDate(d.getDate()+days);return localDate(d)}
const sample="They haven't replied to my message, and I keep thinking I don't matter to them.";
export default function Home(){
 const [tab,setTab]=useState('today'),[saved,setSaved]=useState<Saved>(initial),[ready,setReady]=useState(false),[offline,setOffline]=useState(false),[failure,setFailure]=useState(false);
 const [flow,setFlow]=useState<null|'capture'|'recommend'|'guide'|'sentence'|'success'>(null),[input,setInput]=useState(''),[selected,setSelected]=useState(9),[answers,setAnswers]=useState<Record<string,string>>({}),[sentence,setSentence]=useState(''),[quantity,setQuantity]=useState(1),[busy,setBusy]=useState(false),[voice,setVoice]=useState(false),[error,setError]=useState(''),[last,setLast]=useState('');
 const [filter,setFilter]=useState('All'),[recordFilter,setRecordFilter]=useState('all'),[noteId,setNoteId]=useState<string|null>(null),[recall,setRecall]=useState(''),[revealed,setRevealed]=useState(false),[readMode,setReadMode]=useState(false),[edit,setEdit]=useState<Entry|null>(null),[editText,setEditText]=useState('');
 const [reminders,setReminders]=useState(false),[reminderTime,setReminderTime]=useState('20:30'),[resetOpen,setResetOpen]=useState(false);
 const submitLock=useRef(false),timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const p=practices.find(x=>x.id===selected)!;
 const note=notes.find(x=>x.id===noteId);
 const date=localDate(),day=courseDay(saved.courseStart);
 const today=saved.entries.filter(e=>e.date===date&&!e.revoked&&!e.skipped);
 const count=(id:number)=>today.filter(e=>e.practice===id).reduce((s,e)=>s+e.quantity,0);
 const target=(pr:Practice)=>saved.goals[String(pr.id)]??pr.target;
 const daily=practices.filter(pr=>pr.category==='Daily');
 const activeDaily=daily.filter(pr=>(target(pr)??0)>0);
 const achieved=activeDaily.filter(pr=>count(pr.id)>=(target(pr)??0)).length;
 const latestReview=(id:string)=>saved.reviews.filter(r=>r.note===id&&r.rating!=='Read').at(-1);
 const due=notes.filter(n=>!latestReview(n.id)||latestReview(n.id)!.due<=date);
 useEffect(()=>{try{const raw=localStorage.getItem(key);if(raw){const d=JSON.parse(raw);if(Array.isArray(d.entries)&&Array.isArray(d.reviews)&&d.goals&&typeof d.courseStart==='string')setSaved(d);}}catch{toast.error('Saved demo data could not be read. Starting a new session.')}setReady(true);return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem(key,JSON.stringify(saved))}catch{toast.error('Browser storage is unavailable. Changes will only last for this session.')}},[saved,ready]);
 function openPractice(id:number){setSelected(id);setAnswers({});setQuantity(1);setSentence('');setError('');submitLock.current=false;setFlow('guide')}
 function openCapture(){setInput('');setError('');setBusy(false);setVoice(false);submitLock.current=false;setFlow('capture')}
 function closeFlow(){if(timer.current)clearTimeout(timer.current);setBusy(false);setVoice(false);setFlow(null);setError('')}
 function simulateVoice(){setVoice(true);timer.current=setTimeout(()=>{setInput(sample);setVoice(false)},1400)}
 function analyze(){if(!input.trim())return;setError('');if(offline){setError('AI suggestions are unavailable in offline preview. Choose a practice manually below.');return}setBusy(true);timer.current=setTimeout(()=>{setBusy(false);if(failure){setError('The simulated suggestion service is unavailable. Your text is still here. Retry or choose a practice.');return}setSelected(recommend(input));setFlow('recommend')},650)}
 function generate(){const tidy=(v:string)=>v.trim().replace(/[.!。！]+$/, '');const missing=p.fields.find(f=>!answers[f.key]?.trim());if(missing){setError(`Add a response for “${missing.label}” first.`);return}if(p.id===4&&!answers.intensity){setError('Choose your own intensity rating first.');return}setError('');let draft=p.sentence;if(p.id===3)draft=`What happened: ${tidy(answers.event)}. My response: ${tidy(answers.reaction)}. One next step: ${tidy(answers.next)}.`;if(p.id===4)draft=`I notice ${answers.body} and the thought “${answers.thought}”. I rated this feeling ${answers.intensity}/10. I can observe it without rushing to a conclusion.`;if(p.id===9)draft=`What I observed: ${tidy(answers.event)}. I interpreted it as “${tidy(answers.meaning)}”. I do not know the whole story, and this does not determine my worth.`;setSentence(draft);setFlow('sentence')}
 function complete(skipped=false){if(submitLock.current)return;if(!skipped&&!sentence.trim())return;if(selected===10&&day>7){setError('This seven-day course is complete. Start a new course in Preferences to continue.');return}submitLock.current=true;const id=crypto.randomUUID();const e:Entry={id,practice:selected,quantity:selected===2?quantity:1,sentence:skipped?'No relevant fear situation today.':sentence,answers,time:new Date().toISOString(),date:localDate(),skipped};setSaved(s=>({...s,courseStart:selected===10&&!s.courseStart?localDate():s.courseStart,entries:[...s.entries,e]}));setLast(id);setFlow('success');toast.success(skipped?'Check-in saved without adding to your count.':'Practice saved on this device.');}
 function undo(id:string){setSaved(s=>({...s,entries:s.entries.map(e=>e.id===id?{...e,revoked:true}:e)}));toast('Completion undone. Your progress has been updated.')}
 function openNote(id:string){setNoteId(id);setRecall('');setRevealed(false);setReadMode(false)}
 function saveReview(rating:string){if(!note)return;const prev=latestReview(note.id);const stage=rating==='Again'?0:rating==='Difficult'?(prev?.stage??0):Math.min((prev?.stage??-1)+1,4);const days=rating==='Again'||rating==='Difficult'?1:[1,3,7,14,30][stage];const r:Review={id:crypto.randomUUID(),note:note.id,answer:recall,rating,time:new Date().toISOString(),due:dueDate(days),stage};setSaved(s=>({...s,reviews:[...s.reviews,r]}));setNoteId(null);toast.success(rating==='Read'?'Reading recorded. Recall schedule unchanged.':`Review saved. Next review: ${new Date(r.due+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'})}.`)}
 useEffect(()=>{const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!ctx)return;const c=new AbortController();try{Promise.resolve(ctx.registerTool({name:'start_practice',description:'Open a practice guide without completing or counting it.',inputSchema:{type:'object',properties:{practiceId:{type:'integer',minimum:1,maximum:10}},required:['practiceId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:(x:unknown)=>{const d=x as {practiceId:number};if(!d||!Number.isInteger(d.practiceId)||d.practiceId<1||d.practiceId>10)throw Error('practiceId must be an integer from 1 to 10');flushSync(()=>openPractice(d.practiceId));return {practiceId:d.practiceId,state:'guide',completionRecorded:false}}},{signal:c.signal})).catch(()=>{});}catch{}return()=>c.abort()},[]);
 const recent=[...saved.entries].reverse();
 return <main className="shell"><Toaster position="top-center" richColors/><header className="topbar"><a className="brand" href="/" aria-label="Pause home"><CirclePause/>pause<span>REFLECTION & PRACTICE</span></a><div className="top-right">{offline&&<span className="offline-tag"><WifiOff/> Offline preview</span>}<span className="prototype">Interactive prototype</span><button className="icon-btn" aria-label="Preferences" onClick={()=>setTab('settings')}><Settings2/></button></div></header>
 <Tabs value={tab} onValueChange={setTab} className="workspace"><TabsList className="rail" aria-label="Main navigation">{[{id:'today',label:'Today',Icon:Sun},{id:'practices',label:'Practices',Icon:Layers},{id:'knowledge',label:'Knowledge',Icon:BookOpen},{id:'records',label:'Records',Icon:History},{id:'settings',label:'Preferences',Icon:Settings2}].map(({id,label,Icon})=><TabsTrigger key={id} value={id}><Icon/>{label}</TabsTrigger>)}</TabsList>
 <div className="main">
 <TabsContent value="today"><div className="heading"><div><p className="eyebrow">YOUR DAILY SPACE</p><h1>A little room to pause.</h1><p className="muted">Notice what’s here. Choose what comes next.</p></div><span className="date">{ready?new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'}):'Today'}</span></div>
 <div className="home-grid"><section className="capture-card"><p className="eyebrow">START WHERE YOU ARE</p><h2>What’s on your mind?</h2><p>You don’t need the right words.<br/>Start with what happened.</p><button className="talk" onClick={openCapture}><Mic/>Talk it through<ArrowUpRight/></button><p className="small">Simulated voice · typing works too</p></section><section className="daily-card"><div className="card-top"><p className="eyebrow">A SMALL PRACTICE</p><span className="pill">3 seconds</span></div><CirclePause className="feature-icon"/><h2>Three seconds.<br/>A different response.</h2><p className="muted">Pause. Notice your reaction. Then choose your next step.</p><button className="text-link" onClick={()=>openPractice(1)}>Try a pause <ArrowRight/></button></section></div>
 <div className="section-heading"><h2>Your practice, at your pace</h2><button className="text-link" onClick={()=>setTab('practices')}>View all 10 <ArrowRight/></button></div><div className="progress-panel"><div className="progress-intro"><span className="large-number">{achieved}<span>/ {activeDaily.length}</span></span><p>daily goals met</p><span className="muted">Small moments count.</span></div><div className="progress-list">{daily.slice(0,3).map(pr=><button className="progress-row" key={pr.id} onClick={()=>openPractice(pr.id)}><div><span>{pr.title}</span><span className="muted">{count(pr.id)} / {target(pr)} {pr.unit}</span></div><Progress aria-label={`${pr.title} progress`} value={target(pr)?Math.min(100,count(pr.id)/target(pr)!*100):0}/></button>)}</div></div>
 <div className="bottom-grid"><button className="feature-link" onClick={()=>setTab('knowledge')}><span className="square-icon"><BookOpen/></span><span><strong>Return to what you know</strong><span className="muted">{due.length} notes ready to revisit</span></span><ArrowUpRight/></button><button className="feature-link" onClick={()=>openPractice(10)}><span className="square-icon night"><Moon/></span><span><strong>Close the day</strong><span className="muted">{day>7?'Seven-day course complete':saved.courseStart?`Day ${day} of 7 · ${count(10)?'completed tonight':'an evening ritual'}`:'A seven-day evening ritual'}</span></span><ArrowUpRight/></button></div><p className="privacy-note">Your demo records stay in this browser. Voice and recommendations are simulated.</p></TabsContent>
 <TabsContent value="practices"><div className="heading"><div><p className="eyebrow">THE PRACTICE LIBRARY</p><h1>Find your way back.</h1><p className="muted">Ten ways to notice, reflect, and choose.</p></div><button className="primary" onClick={openCapture}><Mic/>Help me choose</button></div><Tabs value={filter} onValueChange={setFilter}><TabsList className="filter-tabs">{['All','Daily','In the moment','Evening'].map(f=><TabsTrigger key={f} value={f}>{f}</TabsTrigger>)}</TabsList></Tabs><div className="practice-grid">{practices.filter(pr=>filter==='All'||pr.category===filter).map(pr=><button className="practice-tile" key={pr.id} onClick={()=>openPractice(pr.id)}><div className="tile-top"><span className="number">{String(pr.id).padStart(2,'0')}</span><span className="pill">{pr.category}</span></div><h2>{pr.title}</h2><p>{pr.description}</p><div className="tile-bottom"><span>{pr.target===null?`${count(pr.id)} recorded · as needed`:pr.id===10?(day>7?'Course complete':`${count(pr.id)} / 1 tonight`):`${count(pr.id)} / ${target(pr)} ${pr.unit}`}</span><ArrowUpRight/></div></button>)}</div><p className="privacy-note">Daily targets are course defaults. Adjust them in Preferences. In-the-moment practices have no daily quota.</p></TabsContent>
 <TabsContent value="knowledge"><div className="heading"><div><p className="eyebrow">KNOWLEDGE & REFLECTION</p><h1>Make room to remember.</h1><p className="muted">Recall in your own words, then return to the source.</p></div><span className="pill">{due.length} ready to review</span></div><div className="knowledge-list">{notes.map((n,i)=><button className="knowledge-row" onClick={()=>openNote(n.id)} key={n.id}><span className="book-number">0{i+1}</span><div><span className="eyebrow">{n.type}</span><h2>{n.title}</h2><p>{n.question}</p><span className="source">{n.source}</span></div><span className="review-due">{due.some(x=>x.id===n.id)?'Ready to revisit':`Next: ${latestReview(n.id)?.due}`}<ArrowUpRight/></span></button>)}</div><div className="note-callout"><BookOpen/><p>Concept cards use translated course notes. The journal is a fictional example; your private diary is not included.</p></div></TabsContent>
 <TabsContent value="records"><div className="heading"><div><p className="eyebrow">YOUR REFLECTIONS</p><h1>Moments you noticed.</h1><p className="muted">A record of practice, not a score of how you feel.</p></div><Select value={recordFilter} onValueChange={setRecordFilter}><SelectTrigger aria-label="Filter records"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All practices</SelectItem>{practices.map(pr=><SelectItem key={pr.id} value={String(pr.id)}>{pr.title}</SelectItem>)}</SelectContent></Select></div>
 {recent.filter(e=>recordFilter==='all'||e.practice===Number(recordFilter)).length===0?<div className="empty-panel"><History/><h2>Your first moment starts here.</h2><p className="muted">Complete a practice to keep a reflection you can return to.</p><button className="primary" onClick={openCapture}>Start a reflection <ArrowRight/></button></div>:<div className="record-list">{recent.filter(e=>recordFilter==='all'||e.practice===Number(recordFilter)).map(e=><article className={`record ${e.revoked?'revoked':''}`} key={e.id}><div className="record-head"><span className="pill">{practices.find(pr=>pr.id===e.practice)?.title}</span><time>{new Date(e.time).toLocaleString(undefined,{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</time></div><p className="record-sentence">{e.sentence}</p><div className="record-footer"><span className="muted">{e.revoked?'Undone · not counted':e.skipped?'No relevant situation · not counted':`${e.quantity} ${e.practice===2?'sentence(s)':'completion'} · saved on this device`}</span>{!e.revoked&&<div><button className="text-link" onClick={()=>{setEdit(e);setEditText(e.sentence)}}>Edit</button><button className="text-link" onClick={()=>undo(e.id)}><RotateCcw/>Undo</button></div>}</div></article>)}</div>}
 {saved.reviews.length>0&&<section className="review-history"><h2>Knowledge revisited</h2>{[...saved.reviews].reverse().slice(0,8).map(r=><div key={r.id}><BookOpen/><strong>{notes.find(n=>n.id===r.note)?.title}</strong><span>{r.rating} · {new Date(r.time).toLocaleDateString()}</span></div>)}</section>}</TabsContent>
 <TabsContent value="settings"><div className="heading"><div><p className="eyebrow">MAKE IT YOURS</p><h1>A rhythm that fits.</h1><p className="muted">Adjust your goals and explore the prototype’s states.</p></div></div><section className="settings-panel"><h2>Daily practice goals</h2><p className="muted">Course suggestions are a starting point. Zero turns a goal off.</p>{daily.map(pr=><label className="setting-row" key={pr.id}><span>{pr.title}<small>{pr.unit} per day</small></span><input aria-label={`${pr.title} daily goal`} type="number" min="0" max="100" value={target(pr)??0} onChange={e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=0&&v<=100)setSaved(s=>({...s,goals:{...s.goals,[pr.id]:v}}))}}/></label>)}</section><section className="settings-panel"><h2>Evening course</h2><p className="muted">{saved.courseStart?`Started ${saved.courseStart}. ${day>7?'This course is complete.':`Day ${day} of 7.`}`:'Your seven-day course starts when you first complete Close the day.'}</p>{day>7&&<button className="secondary" onClick={()=>setSaved(s=>({...s,courseStart:localDate()}))}>Start another seven days</button>}</section><section className="settings-panel"><h2>Reminder preview</h2><label className="setting-row"><span>Show an evening reminder<small>Preview only; no notifications will be sent.</small></span><Switch checked={reminders} onCheckedChange={setReminders}/></label>{reminders&&<><label className="setting-row"><span>Evening time</span><input type="time" value={reminderTime} onChange={e=>setReminderTime(e.target.value)}/></label><div className="reminder-preview"><Moon/><div><strong>Pause · {reminderTime}</strong><p>There’s a little space for reflection when you’re ready.</p></div></div></>}</section><section className="settings-panel"><h2>Prototype controls</h2><label className="setting-row"><span>Simulate offline<small>Manual practice stays available; suggestions pause.</small></span><Switch checked={offline} onCheckedChange={setOffline}/></label><label className="setting-row"><span>Simulate suggestion failure<small>Test retry and manual selection.</small></span><Switch checked={failure} onCheckedChange={setFailure}/></label><button className="text-link danger" onClick={()=>setResetOpen(true)}>Reset local demo records</button></section><p className="privacy-note">No account, cloud sync, real voice transcription, or background notifications are connected in this prototype.</p></TabsContent>
 </div></Tabs>
 <Dialog open={!!flow} onOpenChange={v=>{if(!v)closeFlow()}}><DialogContent className="flow-dialog" aria-describedby="flow-description"><DialogTitle className="sr-only">{flow==='capture'?'Talk it through':flow==='recommend'?'Choose a practice':flow==='success'?'Practice saved':p.title}</DialogTitle><DialogDescription id="flow-description" className="sr-only">A guided reflection. You control what is recorded.</DialogDescription>
 {flow==='capture'&&<><p className="eyebrow">A MOMENT FOR YOU</p><h2 className="flow-title">What’s happening?</h2><p className="muted">Start with the moment that brought you here.</p><button className={`voice-button ${voice?'listening':''}`} disabled={voice} onClick={simulateVoice}><Mic/>{voice?'Loading a sample transcript…':'Try simulated voice'}</button><p className="demo-label">Demo only. Your microphone is not used.</p><label className="field-label" htmlFor="capture-text">Your words</label><textarea id="capture-text" autoFocus rows={5} value={input} onChange={e=>setInput(e.target.value)} placeholder="Something happened, and I noticed…"/><button className="text-link" onClick={()=>setInput(sample)}>Use an example</button>{error&&<p className="error" role="alert">{error}</p>}<button className="primary full" disabled={!input.trim()||busy||voice} onClick={analyze}>{busy?'Finding a starting point…':'Find a practice'}<ArrowRight/></button><div className="divider"><span>or choose for yourself</span></div><Select onValueChange={v=>openPractice(Number(v))}><SelectTrigger className="full" aria-label="Choose a practice manually"><SelectValue placeholder="Browse the ten practices"/></SelectTrigger><SelectContent>{practices.map(pr=><SelectItem key={pr.id} value={String(pr.id)}>{pr.id}. {pr.title}</SelectItem>)}</SelectContent></Select></>}
 {flow==='recommend'&&<><p className="eyebrow">A POSSIBLE STARTING POINT</p><h2 className="flow-title">Try a little perspective.</h2><div className="input-quote">“{input}”</div><div className="recommendation"><span className="pill">Practice {p.id} · suggested</span><h3>{p.title}</h3><p>{p.cue}</p></div><p className="demo-label">Simulated recommendation using simple topic matching.</p><button className="primary full" onClick={()=>{setAnswers({});setError('');setFlow('guide')}}>Try this practice <ArrowRight/></button><label className="field-label">Another practice may fit better</label><Select value={String(selected)} onValueChange={v=>setSelected(Number(v))}><SelectTrigger className="full" aria-label="Change suggested practice"><SelectValue/></SelectTrigger><SelectContent>{practices.map(pr=><SelectItem key={pr.id} value={String(pr.id)}>{pr.id}. {pr.title}</SelectItem>)}</SelectContent></Select><button className="text-link" onClick={()=>setFlow('capture')}>Edit what I said</button></>}
 {flow==='guide'&&<><div className="step-label"><span className="eyebrow">PRACTICE {String(p.id).padStart(2,'0')} · NOTICE</span><span className="muted"><Clock3/>{p.duration}</span></div><h2 className="flow-title">{p.title}</h2><p className="muted">{p.description}</p><ol className="steps">{p.steps.map((s,i)=><li key={s}><span>{i+1}</span>{s}</li>)}</ol>{p.id===10&&day>7?<div className="note-callout"><Check/><p>This seven-day course is complete. You can start a new one in Preferences.</p></div>:<>{p.id===4&&<><label className="field-label">How intense does it feel?</label><Select value={answers.intensity??''} onValueChange={v=>setAnswers(a=>({...a,intensity:v}))}><SelectTrigger className="full" aria-label="Fear intensity"><SelectValue placeholder="Choose your rating · 0–10"/></SelectTrigger><SelectContent>{Array.from({length:11},(_,i)=><SelectItem key={i} value={String(i)}>{i} — {i===0?'no fear':i===10?'very intense':'out of 10'}</SelectItem>)}</SelectContent></Select></>}{p.fields.map(f=><div className="field" key={f.key}><label htmlFor={`field-${f.key}`} className="field-label">{f.label}</label><textarea rows={2} id={`field-${f.key}`} value={answers[f.key]??''} onChange={e=>setAnswers(a=>({...a,[f.key]:e.target.value}))} placeholder={f.hint}/></div>)}{error&&<p role="alert" className="error">{error}</p>}<button className="primary full" onClick={generate}>Shape my reflection <ArrowRight/></button>{p.id===4&&<button className="text-link" onClick={()=>complete(true)}>No relevant fear situation today</button>}</>}<p className="source-foot">Course source: {p.chinese} · wording adapted for this prototype.</p></>}
 {flow==='sentence'&&<><p className="eyebrow">PRACTICE {String(p.id).padStart(2,'0')} · REFLECT</p><h2 className="flow-title">Make these words yours.</h2><p className="muted">An editable starting point, not the only right response.</p><label className="field-label" htmlFor="sentence">Your reflection</label><textarea className="sentence-input" rows={6} id="sentence" value={sentence} onChange={e=>setSentence(e.target.value)}/><p className="demo-label">Generated from a local template. No AI service is connected.</p>{p.id===2&&<label className="setting-row"><span>Sentences you actually rewrote</span><input type="number" min="1" max="100" value={quantity} onChange={e=>{const n=Number(e.target.value);if(Number.isInteger(n)&&n>0&&n<=100)setQuantity(n)}}/></label>}<div className="completion-note"><Check/><p>Save only after you’ve done the practice. Drafting alone does not add to your count.</p></div><button className="primary full" disabled={!sentence.trim()} onClick={()=>complete()}>I completed this practice <Check/></button><button className="text-link" onClick={()=>setFlow('guide')}>Back to my observations</button></>}
 {flow==='success'&&<div className="success"><span className="success-icon"><Check/></span><p className="eyebrow">A MOMENT NOTICED</p><h2 className="flow-title">You made a little space.</h2><p className="muted">{saved.entries.find(e=>e.id===last)?.skipped?'Your check-in was saved without adding a completion.':'Your reflection is saved on this device.'}</p><div className="success-summary"><strong>{p.title}</strong><span>{p.target===null?`${count(p.id)} recorded today`:p.id===10?`${count(p.id)} / 1 tonight`:`${count(p.id)} / ${target(p)} ${p.unit} today`}</span></div><button className="primary full" onClick={()=>{closeFlow();setTab('today')}}>Back to today <ArrowRight/></button><button className="text-link" onClick={()=>{undo(last);closeFlow()}}><RotateCcw/>Undo this completion</button></div>}
 </DialogContent></Dialog>
 <Dialog open={!!note} onOpenChange={v=>{if(!v)setNoteId(null)}}><DialogContent className="flow-dialog"><DialogTitle className="sr-only">{note?.title}</DialogTitle><DialogDescription className="sr-only">Recall a note, compare with its source, and choose a review interval.</DialogDescription>{note&&<><p className="eyebrow">{note.type} · KNOWLEDGE REVIEW</p><h2 className="flow-title">{note.title}</h2><p className="review-question">{note.question}</p>{!revealed?<><label className="field-label" htmlFor="recall">In your own words</label><textarea rows={5} id="recall" value={recall} onChange={e=>setRecall(e.target.value)} placeholder={note.hint}/><button className="text-link" onClick={()=>setRecall(note.sample)}><Mic/>Use a simulated spoken response</button><button className="primary full" disabled={!recall.trim()} onClick={()=>setRevealed(true)}>Compare with the note <ArrowRight/></button><button className="text-link" onClick={()=>{setReadMode(true);setRevealed(true)}}>I’d rather read today</button></>:<>{!readMode&&<div className="recall-answer"><span className="eyebrow">YOUR RECALL</span><p>{recall}</p></div>}<div className="source-note"><span className="eyebrow">THE ORIGINAL IDEA</span><p>{note.body}</p><span className="source">Source: {note.source}</span></div><p className="muted review-hint">{note.type==='Journal'?'Notice how your perspective has changed. There is no correct answer.':'Compare the main ideas. What did you remember, leave out, or add? This prototype does not automatically grade your recall.'}</p>{readMode?<button className="primary full" onClick={()=>saveReview('Read')}>Save as reading <Check/></button>:<><label className="field-label">How did that feel?</label><div className="rating-buttons"><button onClick={()=>saveReview('Again')}>Again<span>Tomorrow</span></button><button onClick={()=>saveReview('Difficult')}>Difficult<span>Tomorrow</span></button><button onClick={()=>saveReview('Understood')}>Understood<span>Next interval</span></button></div></>}</>}</>}</DialogContent></Dialog>
 <Dialog open={!!edit} onOpenChange={v=>{if(!v)setEdit(null)}}><DialogContent className="flow-dialog"><DialogTitle>Edit your reflection</DialogTitle><DialogDescription>Editing words does not change your practice count.</DialogDescription><textarea aria-label="Edit reflection" rows={6} value={editText} onChange={e=>setEditText(e.target.value)}/><button className="primary full" disabled={!editText.trim()} onClick={()=>{setSaved(s=>({...s,entries:s.entries.map(e=>e.id===edit?.id?{...e,sentence:editText}:e)}));setEdit(null);toast.success('Reflection updated.')}}>Save changes</button></DialogContent></Dialog>
 <AlertDialog open={resetOpen} onOpenChange={setResetOpen}><AlertDialogContent className="flow-dialog"><AlertDialogTitle>Reset demo records?</AlertDialogTitle><AlertDialogDescription>This removes this browser’s practice history, review history, and custom goals. Your Obsidian notes are not affected.</AlertDialogDescription><AlertDialogAction className="primary full" onClick={()=>{setSaved(initial);toast('Local demo records reset.')}}>Reset demo records</AlertDialogAction><AlertDialogCancel className="secondary">Keep my records</AlertDialogCancel></AlertDialogContent></AlertDialog>
 </main>
}
