export type Field = {key:string;label:string;hint:string};
export type Practice = {id:number;title:string;chinese:string;description:string;category:'Daily'|'In the moment'|'Evening';target:number|null;unit:string;duration:string;steps:string[];fields:Field[];sentence:string;cue:string};
const event={key:'event',label:'What happened?',hint:'Only what you could observe.'};
const reaction={key:'reaction',label:'What did you notice in yourself?',hint:'A feeling, thought, or physical sensation.'};
export const practices:Practice[]=[
{id:1,title:'Three-second pause',chinese:'三秒死亡指令',description:'Create a little space between a moment and your response.',category:'Daily',target:20,unit:'pauses',duration:'3 seconds',steps:['Pause the automatic response.','Notice: a reaction is happening.','Return to the present, then choose.'],fields:[event],sentence:'I can pause for three seconds, notice my reaction, and choose what comes next.',cue:'An immediate pause can help you notice your response before acting.'},
{id:2,title:'Name the state',chinese:'载体命名法',description:'Describe what you feel without making it your whole identity.',category:'Daily',target:10,unit:'sentences',duration:'A brief reflection',steps:['Notice your original “I am…” sentence.','Describe a state or experience instead of a fixed identity.','Save the wording that feels true to you.'],fields:[{key:'original',label:'What was your original sentence?',hint:'For example: “I am a failure.”'}],sentence:'I am noticing a difficult feeling right now. It describes this moment, not all of who I am.',cue:'Your wording describes an inner state; try separating that state from your identity.'},
{id:3,title:'Separate the three layers',chinese:'银幕事件三分法',description:'See the event, your response, and your next step separately.',category:'Daily',target:3,unit:'reflections',duration:'2–3 minutes',steps:['Write down the observable event.','Notice your internal reaction.','Choose a response without rushing.'],fields:[event,reaction,{key:'next',label:'What is one possible next step?',hint:'Something small and within your control.'}],sentence:'I can separate what happened from my reaction, and choose one grounded next step.',cue:'This is a useful starting point when facts, feelings, and interpretations are tangled together.'},
{id:4,title:'Map the fear',chinese:'恐惧还原为载体讯号',description:'Give a difficult feeling a shape you can observe.',category:'Daily',target:1,unit:'check-in',duration:'2 minutes',steps:['Rate the intensity yourself, from 0 to 10.','Notice where you feel it and what the thought says.','Observe the experience without treating the thought as a fact.'],fields:[{key:'body',label:'Where do you notice it?',hint:'Describe the location, or write “not sure”.'},{key:'thought',label:'What is the worried thought saying?',hint:'Use the words that are actually coming up.'}],sentence:'I notice this feeling and this thought. I can observe them without needing to reach a conclusion right now.',cue:'You mentioned fear or anxiety. A structured check-in can help describe what you are experiencing.'},
{id:5,title:'Notice the familiar role',chinese:'辨识从玩家回到角色',description:'Recognize the “I must” or “I’m not enough” pattern.',category:'In the moment',target:null,unit:'times',duration:'When needed',steps:['Notice urgent or absolute language.','Name the pattern without judging it.','Pause before responding.'],fields:[{key:'thought',label:'Which phrase caught your attention?',hint:'For example: “I have to fix this immediately.”'}],sentence:'I notice an urgent, familiar way of thinking. I can pause before following it.',cue:'Urgent or absolute language may be a familiar response pattern you want to notice.'},
{id:6,title:'Return to the body',chinese:'身体不是我 载体扫描',description:'Spend five quiet minutes noticing your body and breath.',category:'Daily',target:1,unit:'scan',duration:'5 minutes',steps:['Notice your head, chest, and stomach.','Bring attention to your breathing without forcing it.','Feel the support beneath your body.'],fields:[{key:'observation',label:'What did you notice?',hint:'A simple observation is enough.'}],sentence:'I am here, noticing my body, my breathing, and the support beneath me.',cue:'A body scan is a routine you can choose whenever you want a quiet check-in.'},
{id:7,title:'Numbers, not self-worth',chinese:'财务界面去身份化',description:'Look at financial information without turning it into a verdict.',category:'In the moment',target:null,unit:'times',duration:'At least 10 seconds',steps:['Name the financial data you actually see.','Notice your reaction.','Choose a practical next step. Financial responsibilities still need attention.'],fields:[event,reaction,{key:'next',label:'What needs practical attention?',hint:'For example: check a balance or review a bill.'}],sentence:'This number is information I can work with. It does not define my value.',cue:'You mentioned financial information. This practice separates the data from your sense of self-worth.'},
{id:8,title:'Listen without catastrophizing',chinese:'身体讯号去灾难化',description:'Separate a physical signal from the story your mind adds.',category:'In the moment',target:null,unit:'times',duration:'When needed',steps:['Describe the actual physical signal.','Notice the interpretation you are adding.','Choose appropriate real-world care. This reflection does not replace medical judgment.'],fields:[{key:'symptom',label:'What do you physically notice?',hint:'Describe the sensation without guessing its cause.'},{key:'thought',label:'What are you afraid it means?',hint:'Separate this interpretation from the sensation.'},{key:'next',label:'What practical care will you take?',hint:'Record your own appropriate next step.'}],sentence:'I notice a physical signal and my worry about it. I can respond to the situation with appropriate care.',cue:'You mentioned a physical sensation. Separate what you notice from what you fear it means.'},
{id:9,title:'Their response, your worth',chinese:'他人剧情去主权化',description:'Separate someone else’s behavior from what it means about you.',category:'In the moment',target:null,unit:'times',duration:'2 minutes',steps:['Describe what the other person actually did.','Notice the meaning you gave it.','Leave room for what you do not know.'],fields:[event,{key:'meaning',label:'What meaning did you give it?',hint:'For example: “They don’t value me.”'}],sentence:'I do not yet know what their response means. It does not determine my worth.',cue:'You described an interpersonal situation. This practice separates someone’s behavior from your interpretation.'},
{id:10,title:'Close the day',chinese:'睡前玩家封存',description:'Let today be complete enough to rest.',category:'Evening',target:1,unit:'closure',duration:'3 minutes · 7-day course',steps:['Let the day’s events be recorded rather than replayed.','Notice one moment that stayed with you.','Allow your body to rest. Unfinished tasks can wait.'],fields:[{key:'release',label:'What can you set down for tonight?',hint:'You do not have to solve it here.'}],sentence:'Today can end here. I can return to unfinished things tomorrow and allow myself to rest now.',cue:'This is the evening closing practice for your seven-day course.'}
];
export const notes=[
{id:'response',title:'The first response',type:'Concept',source:'无延迟反射矩阵',question:'What happens in the first moment after an event?',body:'The body can react within fractions of a second after something happens.',hint:'Recall the timing of the reaction and what you might notice.',sample:'There can be a very quick physical reaction before I have put the event into words.'},
{id:'patterns',title:'Familiar patterns',type:'Concept',source:'旧系统',question:'Which familiar responses can you recognize?',body:'Wanting to hold on, defend, explain, prove, seek help, or control.',hint:'Try recalling several responses, then compare with the note.',sample:'I sometimes notice the urge to explain, defend, prove myself, or control the outcome.'},
{id:'position',title:'The observing position',type:'Course note',source:'Acceptance Criteria',question:'What does the course mean by changing your observing position?',body:'The course emphasizes noticing an experience rather than treating it as the whole self. Its focus is an observing position rather than finding a perfect answer.',hint:'Describe the course viewpoint in your own words.',sample:'I can notice what is happening without treating this one experience as all of who I am.'},
{id:'journal',title:'A moment worth revisiting',type:'Journal',source:'Sample journal · not your private diary',question:'How does this moment look to you now?',body:'Today I paused before answering a difficult message. I still felt uncertain, but I gave myself time to choose my words.',hint:'There is no correct answer. Reflect on what changed or stayed the same.',sample:'The uncertainty did not disappear, but taking a moment helped me choose a calmer response.'}
];
export function recommend(text:string):number{if(/money|balance|bill|finance|income|price|钱|财务|余额/i.test(text))return 7;if(/pain|heart|headache|symptom|身体|疼|心悸/i.test(text))return 8;if(/reply|replied|friend|partner|message|ignored|回复|关系|批评|冷淡/i.test(text))return 9;if(/afraid|fear|anxious|anxiety|恐惧|害怕|焦虑/i.test(text))return 4;if(/must|immediately|have to|必须|立刻|完了/i.test(text))return 5;if(/i am|i'm|我很|我是/i.test(text))return 2;return 3;}
